name: Adding Media Event
description: A quick form for adding media to TWDB
title: "[ADD EVENT]: "
labels:
  - enhancement
assignees:
  - DLBPointon

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!

  - type: input
    id: movie_title
    attributes:
      label: Movie Title
      description: Title of the media you want to add to the database
      placeholder: Alien
    validations:
      required: false

  - type: input
    id: imdb_code
    attributes:
      label: IMDB Code
      description: So I can pull all of the details about the media.
      placeholder: tt0078748
    validations:
      required: false

  - type: input
    id: timespan
    attributes:
      label: Time Span
      description: So that we can most accurately inform people which part of the media to avoid, what minute did the event start and finish?
      placeholder: 25-42
    validations:
      required: false

  - type: dropdown
    id: media_type
    attributes:
      label: Media Type
      description: What type of media is this?
      options:
        - Movie
        - TV Show
    validations:
      required: true

  - type: dropdown
    id: event_type
    attributes:
      label: Event Type
      description: What type of event is this?
      options:
        - Birth Event
        - Baby Loss
        - Parent Loss
        - Sexual Violence
        - Car Crash
        - Psychological Abuse
        - Physical Abuse
        - Other
    validations:
      required: true

  - type: textarea
    id: event_description
    attributes:
      label: Event Description
      description: If you can, please describe the event as much as you can. If you can't then just type "HP" or "Help Please" and I'll find it myself.
      placeholder: Describe what happens and when
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to use this form for real events only.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
